language: scala

scala:
  - 2.11.12
  - 2.12.12
  - 2.13.4

jdk:
  - openjdk8

matrix:
  include:
  - jdk: openjdk11
    dist: xenial
    scala: 2.12.12

script:
  - sbt "++${TRAVIS_SCALA_VERSION}" test checkScalariform

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/
    - $HOME/.coursier
