language: scala

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.8
  - 2.13.0-M5

jdk:
  - oraclejdk8

matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.8

script:
  - sbt "++${TRAVIS_SCALA_VERSION}!" test checkScalariform
